### ISSUE TITLE
The code seems to not matched with the paper

### ISSUE THREAD

**Issue by mei-scu** [wjchaoGit/Group-Activity-Recognition#15]
In the paper, the author declared that "we uniformly sample a set of K frames from the video " and K=3, however, in the source code, the data processing function(collective_read_annotations) reads the data every ten frames, that is to say, a video sequence sampled at least a dozen frames of images, so, how to explain it?

**Comment by mei-scu** [comment]
@wjchaoGit  could you please explain it?

**Comment by wjchaoGit** [comment]
Each example(video clip) in the dataset has 10 frames.
During training, we sample a set of 3 frames from the video clip ：https://github.com/wjchaoGit/Group-Activity-Recognition/blob/5bf7d60ed4f5ee3adc2263c0a97e3ee056f682b0/collective.py#L142
During test, we perform dense sampling：https://github.com/wjchaoGit/Group-Activity-Recognition/blob/5bf7d60ed4f5ee3adc2263c0a97e3ee056f682b0/collective.py#L146

**Comment by mei-scu** [comment]
> Each example(video clip) in the dataset has 10 frames.
> During training, we sample a set of 3 frames from the video clip ：
> 
> https://github.com/wjchaoGit/Group-Activity-Recognition/blob/5bf7d60ed4f5ee3adc2263c0a97e3ee056f682b0/collective.py#L142
> 
> 
> During test, we perform dense sampling：
> https://github.com/wjchaoGit/Group-Activity-Recognition/blob/5bf7d60ed4f5ee3adc2263c0a97e3ee056f682b0/collective.py#L146

Thanks for your reply, but the hyper-parameter "self.is_finetune" is true when training stage==1 ,so `       
   if self.is_finetune:
            if self.is_training:
                fid=random.randint(src_fid, src_fid+self.num_frames-1)
                return [(sid, src_fid, fid)]`
 in this way, the code only sampled an image, may I ask is my understanding right?

**Comment by wjchaoGit** [comment]
Yes，you are right.

**Comment by mei-scu** [comment]
> Yes，you are right.

Thanks

**Comment by qdinfish** [comment]
@wjchaoGit  So when do training,  only sampled 1 frame, not 3?
