### ISSUE TITLE
a question in collective.py

### ISSUE THREAD

**Issue by seamanj** [wjchaoGit/Group-Activity-Recognition#3]
Dear Author

Thanks for your kind sharing.

I had a little question about the function `load_samples_sequence()` in collective.py.
Actually, the `src_fid` and `fid` are different. the code read image according to `fid`, while other data are based on `src_fid`. Therefore, when `return images, bboxes,  actions, activities, bboxes_num`, only the `images` is the info of `fid`, other data are actually info of 'src_fid'. 

So my question is why they are different to refer to different frame? I am a little confused. Thanks in advance. :)

**Comment by wjchaoGit** [comment]
Every 10th frame in the Collective Dataset was annotated with image location of person, activity id(http://vhosts.eecs.umich.edu/vision//activity-dataset.html). 

So, each frame gets bboxes/actions/activities/bboxes_num from src_fid.

**Comment by seamanj** [comment]
Thanks for your reply. 

You are right , each frame gets bboxes_num from src_fid, and each frame also gets bboxs(4 corners) from src_fid. Therefore, each frame will have the same bounding box as the src_fid. However, the bounding box is moving among different frame. so why do not we use their own (i.e. fid's) bounding box instead of the src_fid's bounding box?

Thanks again:)

**Comment by wjchaoGit** [comment]
You are right, but i remember that some frames were not annotated with ground-truth bboxes. We have not access to their G.T. bboxes. Therefore, only src_fid's  bboxes can be used as fid's bboxes.

**Comment by seamanj** [comment]
got it, thank you very much!
