### ISSUE TITLE
a question about the action and activity score

### ISSUE THREAD

**Issue by seamanj** [wjchaoGit/Group-Activity-Recognition#4]
Hi , author

I am coming back again xd.

When I debug the code, I found out the score of action and activity can be negative, and the sum of  the score is not equal to 1. Is that normal?

Thanks again :)

**Comment by seamanj** [comment]
I solved it :)

**Comment by seamanj** [comment]
I solved it

**Comment by DeepaliVerma** [comment]
Mam/Sir, I also want to ask the same ques as asked by mam #4  . Please brief me if you resolved it.
